# Site Settings
title: Andrew's Resume
url: 
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Andrew Jones
tagline: Data Scientist
pic: Profile Pic 100.100.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Driven and entreprenuerial quantitative analyst with a strong background in core business skills.


#sidebar links
email: jones5am.aj@gmail.com
phone: 571 262 9461
website: 
linkedin: andrew-jones112358
github: jones5am
twitter: 
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
